### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by sn-kburnett** [ErdbeerenindenBergen/github-crash-course#1]
I think it looks better if the main title is a bit more orange. 

The styling rule code could be changed like this: 

```css
h1 {
  color: #f0a82c;
}
```
